S5t18 Подключено API регистрации
odessa-yandex-praktikum/crazy-bomber pull request #10
Opened 2021-05-21 16:20 UTC by SashaMalova

2021-05-21 18:26 UTC, lalalilulu commented on src/pages/signin/index.tsx
> +            onChange={handleEmailChange}
По идее нужно еще добавить value в компонент и передавать значение, которые мы вводим. Сейчас не уходит ошибка, что поле не заполнено: 
![image](https://user-images.githubusercontent.com/39400036/119182012-102c1400-ba7b-11eb-9409-e23dbdd95832.png)
Если я неправильно заполняю поля, то нет сообщения об ошибке на форме - может добавить, чтобы оповестить пользователя о некорректном заполнении?

2021-05-21 18:41 UTC, lalalilulu requested changes
Посмотри, пожалуйста,  комментарии

2021-05-21 18:41 UTC, lalalilulu commented on src/pages/signin/index.tsx
> +            key="name"
Можно добавить вадидацию для полей: 
- текст - что передаем литералы 
- email - например такой export const isCorrectEmail = (validatedInput) => /^\S+@\S+\.\S+$/.test(validatedInput);
- проверка совпадения паролей

2021-05-21 18:41 UTC, lalalilulu commented on src/pages/signin/index.tsx
>              textError={translations.error.errorTextEmptyField}
У email лучше сделать тип email

2021-05-21 18:41 UTC, lalalilulu commented on src/pages/signin/index.tsx
> +    const [login, setLogin]: [string, (args: string) => void] = useState('');
можно объединить инпуты - по сути их заполнение совпадает. Ниже пример js кода для двух значений - если так использовать, то можно написать общую функцию на обработку ввода данных для инпут полей 
 const [inputs, setInputs] = useState({
        email: "",
        password: ""
    });
    const {email, password} = inputs; 


const handleChange = (e: ChangeEvent<HTMLInputElement>) =>  {
        const {name, value} = e.target;
        setInputs(inputs => ({...inputs, [name]: value}));
    }

2021-05-21 19:04 UTC, SashaMalova commented on src/pages/signin/index.tsx
>              textError={translations.error.errorTextEmptyField}
Поправила

2021-05-21 19:22 UTC, SashaMalova commented on src/pages/signin/index.tsx
> +    const [login, setLogin]: [string, (args: string) => void] = useState('');
Объединила

2021-05-22 20:45 UTC, SashaMalova commented on src/pages/signin/index.tsx
> +            onChange={handleEmailChange}
Добавила валидацию. Ошибки теперь показываются при некорректном заполнении. email должен содержать@ и ., пароли совпадать и пароль, логин, имя не меньше 3 и не больше 15 символов. ошибки показываются, только если курсор был в инпуте и переведен оттуда. кнопка неактивна, если в инпутах есть ошибки.

2021-05-22 20:48 UTC, SashaMalova commented on src/pages/signin/index.tsx
> +    const [login, setLogin]: [string, (args: string) => void] = useState('');
С появлением валидации, этот код пришлось поменять.

2021-05-23 09:20 UTC, lalalilulu approved these changes
Все хорошо

2021-05-25 13:10 UTC, bercly0b commented on src/pages/login/index.tsx
> +    const onSignInClick = (): void => {
давай обернем в [useCallback](https://ru.reactjs.org/docs/hooks-reference.html#usecallback)

2021-05-25 13:11 UTC, bercly0b commented on src/pages/signin/index.tsx
> +    useEffect(() => {}, []);
зачем?)

2021-05-25 13:11 UTC, bercly0b commented on src/pages/signin/index.tsx
> +    const onSignUpClick = (): void => {
[useCallback](https://ru.reactjs.org/docs/hooks-reference.html#usecallback)

2021-05-25 13:12 UTC, bercly0b commented on src/pages/login/index.tsx
> +    const login = useInput('', {isEmpty: true, minLength: 3, maxLength: 15});
`isEmpty` точно нужно передавать? я бы его внутри хука вычислял на основе первого аргумента

2021-05-25 13:14 UTC, bercly0b commented on src/hoc/use-validation.tsx
> +    validations: {[key: string]: boolean | number | string}
давай тут `key` в типизации сделаем не любой строкой, а уточним доступные значения
```
type validationKey = 'minLength' | 'maxLength' | ...
validations: {[key: validationKey]: boolean | number | string}
```

2021-05-25 13:14 UTC, bercly0b commented on src/hoc/use-input.tsx
> +    const onChange = (e: ChangeEvent<HTMLInputElement>) => {
useCallback

2021-05-25 13:15 UTC, bercly0b commented on src/hoc/use-input.tsx
> +    const onBlur = () => {
useCallback

2021-05-25 13:17 UTC, bercly0b commented on src/hoc/use-validation.tsx
> +    return {
точно ли тут нужно так много данных возвращать?
кажется будет понятнее, если хук вернет такую структуру данных
```
{
  isValid: boolean,
  errorText?: string,
}
```

2021-05-25 13:18 UTC, bercly0b commented on src/hoc/use-validation.tsx
> +        for (const validation in validations) {
если на первой проверке value не проходит валидацию, наверное и дальше валидировать его нет смысла

2021-05-25 13:18 UTC, bercly0b commented on src/hoc/use-validation.tsx
> +    return {
тогда не нужно будет столько `useState` вначале хука)

2021-05-25 13:19 UTC, bercly0b commented on src/hoc/use-validation.tsx
> +    return {
хватит одного `const [inputValid, setInputValid] = useState(false);`

2021-05-25 13:19 UTC, bercly0b requested changes
пройдись по комментам пож

2021-05-25 19:03 UTC, SashaMalova commented on src/pages/signin/index.tsx
> +    useEffect(() => {}, []);
убрала

2021-05-25 20:08 UTC, SashaMalova commented on src/pages/login/index.tsx
> +    const onSignInClick = (): void => {
Сделано

2021-05-25 20:09 UTC, SashaMalova commented on src/pages/signin/index.tsx
> +    const onSignUpClick = (): void => {
Сделано

2021-05-25 20:25 UTC, SashaMalova commented on src/pages/login/index.tsx
> +    const login = useInput('', {isEmpty: true, minLength: 3, maxLength: 15});
поправила

2021-05-25 21:36 UTC, SashaMalova commented on src/hoc/use-validation.tsx
> +    validations: {[key: string]: boolean | number | string}
на вот это [key: validationKey] ts ругался, переписала через enum

2021-05-25 22:39 UTC, SashaMalova commented on src/hoc/use-validation.tsx
> +    return {
поправила

2021-05-25 23:19 UTC, SashaMalova commented on src/hoc/use-validation.tsx
> +        for (const validation in validations) {
поправила

2021-05-25 23:20 UTC, SashaMalova commented on src/hoc/use-input.tsx
> +    const onChange = (e: ChangeEvent<HTMLInputElement>) => {
Сделано

2021-05-25 23:20 UTC, SashaMalova commented on src/hoc/use-input.tsx
> +    const onBlur = () => {
Сделано

2021-05-26 14:31 UTC, bercly0b commented on src/hoc/use-validation.tsx
> +        if (errorText !== '') {
можно так `setInputValid(errorText === '')`
а вообще лучше бы в `errorText` записывать `null` а не пустую строку, если ошибок нет

2021-05-26 14:32 UTC, bercly0b commented on src/hoc/use-validation.tsx
> +        validations.forEach((validation: Validation) => {
`forEach` все равно по всем пройдет полям. 
[some](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/some)

2021-05-26 14:32 UTC, bercly0b approved these changes

2021-05-26 19:34 UTC, SashaMalova commented on src/hoc/use-validation.tsx
> +        if (errorText !== '') {
Поправила

2021-05-26 19:41 UTC, SashaMalova commented on src/hoc/use-validation.tsx
> +        validations.forEach((validation: Validation) => {
Поправила

2021-05-26 19:56 UTC, merged