S6t24 Подключено API изменения данных и валидация на странице профиля
odessa-yandex-praktikum/crazy-bomber pull request #15
Opened 2021-05-29 22:04 UTC by SashaMalova

Сейчас данные авторизованного пользователя берутся из заглушки, позже подключим redux
![2021-05-30_01-00-36](https://user-images.githubusercontent.com/78325304/120085660-bb277800-c0e2-11eb-91e2-c3e278bde36a.png)
На моем экране верстка немного разъезжалась, поэтому подправила стили, посмотрите как у Вас сейчас отображается.

2021-05-30 14:55 UTC, lalalilulu commented on src/pages/login/login.css
> -
со стилями все отлично: 
![profile-new](https://user-images.githubusercontent.com/39400036/120108992-41d66680-c170-11eb-8074-61fdd298498f.png)

2021-05-30 14:58 UTC, lalalilulu commented on src/services/api/index.tsx
> +export function changeUserProfile(formData: Data): Promise<Response> {
Если ничего не изменить и нажать save changes - возникает ошибка, но она никак не отображается на ui 
![401-no_message](https://user-images.githubusercontent.com/39400036/120109084-9548b480-c170-11eb-8d2f-a7bab924683d.JPG)

2021-05-30 14:59 UTC, lalalilulu commented on src/services/api/index.tsx
> +export function changePassword(formData: Data): Promise<Response> {
не получается изменить пароль, внести правку в профиль - 
![message](https://user-images.githubusercontent.com/39400036/120109107-b6110a00-c170-11eb-8e10-17e4341c5ca8.JPG)
@SashaMalova у тебя изменения происходит, отрабатывает API?

2021-05-30 15:00 UTC, lalalilulu requested changes
Пожалуйста, посмотри комментарии

2021-05-30 15:00 UTC, lalalilulu commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить API для изменения профиля пользователя.](https://trello.com/c/dJSjoo0i/24-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-api-%D0%B4%D0%BB%D1%8F-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BF%D1%80%D0%BE%D1%84%D0%B8%D0%BB%D1%8F-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F)

2021-05-30 15:08 UTC, lalalilulu commented on src/services/api/index.tsx
> +export function changePassword(formData: Data): Promise<Response> {
поняла - пользователя нет, поэтому и невозможно внести правки

2021-05-30 15:08 UTC, lalalilulu approved these changes

2021-05-30 18:49 UTC, SashaMalova commented on src/services/api/index.tsx
> +export function changeUserProfile(formData: Data): Promise<Response> {
У тебя пользователь не авторизован, мы же профиль будем только авторизованным показывать, а для неавторизованных переадресация на логин.

2021-05-31 15:15 UTC, bercly0b commented on src/hoc/use-input.tsx
> +export const useInput = (initialValue: string, validations: Validation[], mayBeEmpty?: boolean) => {
может вместо `mayBeEmpty` в `validations` добавить `required` ?
что бы не плодить аргументы, есть же уже структура данных для правил валидации

2021-05-31 15:16 UTC, bercly0b approved these changes

2021-05-31 21:24 UTC, merged

2021-05-31 21:25 UTC, SashaMalova commented on src/hoc/use-input.tsx
> +export const useInput = (initialValue: string, validations: Validation[], mayBeEmpty?: boolean) => {
Поправила