S6 t8 Подключено fullscreen API
odessa-yandex-praktikum/crazy-bomber pull request #16
Opened 2021-05-30 23:07 UTC by SashaMalova

2021-05-30 23:07 UTC, SashaMalova commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить  WEB API (кроме Canvas и Fetch).](https://trello.com/c/wNeQoqzM/8-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-web-api-%D0%BA%D1%80%D0%BE%D0%BC%D0%B5-canvas-%D0%B8-fetch)

2021-05-31 19:46 UTC, lalalilulu approved these changes
все хорошо, только на основном экране - в fullscreen немного верстка поехала: 
![image](https://user-images.githubusercontent.com/39400036/120235120-09af5080-c262-11eb-8633-3f8cddd59921.png)

2021-06-02 15:21 UTC, bercly0b commented on src/components/full-screen/index.tsx
> +    function onFullScreenClick() {
давай в `useCallback` обернем?

2021-06-02 15:23 UTC, bercly0b commented on src/hoc/use-input.tsx
> +export const useInput = (initialValue: string, validations: Validation[], mayBeEmpty?: boolean) => {
я уже писал где коммент, возможно не тебе.
не понятно зачем делать отдельный аргумент, когда у   нас уже есть структура данных `validations`, где хранятся правила валидации, давай просто туда добавим  поле `required` ?

2021-06-02 15:26 UTC, bercly0b commented on src/pages/login/index.tsx
> +                if (response.status === 200) {
по хорошему компонент не должен  заниматься логикой проверки статуса запроса и парсингом json 
это должно находится внутри `apiSignIn`, а сюда должен придти либо резолв с данными либо реджект с ошибкой.

мы же в теории  можем захотеть использовать `apiSignIn` в нескольких местах. и в текущей реализации во всех местах придется проверять статус ответа и парсить джейсон..

2021-06-02 15:28 UTC, bercly0b commented on src/services/api/index.tsx
> +export function getUserInfo(): Promise<Response> {
[тоже самое](https://github.com/odessa-yandex-praktikum/crazy-bomber/pull/16#discussion_r644076132)

тут самое  место, для того что бы распарсить ответ, проверить код, подготовить данные либо ошибку для передачи дальше

2021-06-02 15:28 UTC, bercly0b requested changes
пройдись по комментам пож

2021-06-02 19:41 UTC, SashaMalova commented on src/components/full-screen/index.tsx
> +    function onFullScreenClick() {
сделано

2021-06-02 19:42 UTC, SashaMalova commented on src/hoc/use-input.tsx
> +export const useInput = (initialValue: string, validations: Validation[], mayBeEmpty?: boolean) => {
Да, я правила, но это было в другой задаче и ветке, сделала rebase

2021-06-03 20:20 UTC, SashaMalova commented on src/pages/login/index.tsx
> +                if (response.status === 200) {
Поправила

2021-06-03 21:25 UTC, SashaMalova commented
Верстку тоже поправила

2021-06-03 21:26 UTC, SashaMalova commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить  WEB API (кроме Canvas и Fetch).](https://trello.com/c/wNeQoqzM/8-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-web-api-%D0%BA%D1%80%D0%BE%D0%BC%D0%B5-canvas-%D0%B8-fetch)

2021-06-08 14:31 UTC, bercly0b approved these changes

2021-06-08 14:31 UTC, merged