S6T6: добавлено Redux-хранилище и Redux Thunk
odessa-yandex-praktikum/crazy-bomber pull request #17
Opened 2021-05-31 19:20 UTC by lalalilulu

Добавлены Redux store, редьюсеры и экшены, переделаны запросы на авторизацию и логин

2021-05-31 19:21 UTC, lalalilulu commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить Redux-хранилище/ Добавить в проект Redux Thunk (или Redux Saga)](https://trello.com/c/m7AP3QzR/6-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-redux-%D1%85%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B5-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B2-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82-redux-thunk-%D0%B8%D0%BB%D0%B8-redux-saga)

2021-06-01 20:07 UTC, SashaMalova approved these changes
всё хорошо. коммент посмотри.

2021-06-01 20:07 UTC, SashaMalova commented on src/store/actions/userActions.ts
> +                    //fake testdata
Если поребейзишь с последним комитом в ветке 6 спринта там уже есть функция getUserInfo() в /services/api. Можно заменить фейковые данные.

2021-06-02 10:11 UTC, lalalilulu commented on src/store/actions/userActions.ts
> +                    //fake testdata
при вызове getUserInfo - получаю респонс про невалидные куки

2021-06-03 15:29 UTC, bercly0b commented on src/services/api/index.tsx
> +    return fetch(url + apiHost.getUserInfo, {
посмотри пож этот [комент](https://github.com/odessa-yandex-praktikum/crazy-bomber/pull/16#discussion_r644078009) из соседнего ПР

2021-06-03 15:31 UTC, bercly0b commented on src/pages/profile/index.tsx
> +            onChange={(e) => name.onChange(e)}
анонимные  функции лучше оборачивать в `useCallback`, потому что в таком виде для них на каждый ререндер будет создавать новая ссылка, и это будет  считать новыми данными, что вызовет ререндер дочернего компонента, даже если на самом деле  его пропсы не изменились

2021-06-03 15:32 UTC, bercly0b requested changes
пройдись по коментам  пож

2021-06-04 13:56 UTC, lalalilulu commented on src/services/api/index.tsx
> +    return fetch(url + apiHost.getUserInfo, {
изменено и поправлено

2021-06-04 13:57 UTC, lalalilulu commented on src/pages/profile/index.tsx
> +            onChange={(e) => name.onChange(e)}
исправлено на страницы регистрации и логина для всех инпутов

2021-06-08 14:34 UTC, bercly0b approved these changes

2021-06-08 14:47 UTC, merged