S5T17 верстка страниц авторизации и регистрации
odessa-yandex-praktikum/crazy-bomber pull request #3
Opened 2021-05-06 21:14 UTC by SashaMalova

2021-05-06 21:20 UTC, SashaMalova commented
![](https://github.trello.services/images/mini-trello-icon.png) [Сделать страницу логина и страницу регистрации](https://trello.com/c/3RVRsmkn/17-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%83-%D0%BB%D0%BE%D0%B3%D0%B8%D0%BD%D0%B0-%D0%B8-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%83-%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D0%B8)

2021-05-08 11:39 UTC, tomasedk reviewed
Можешь, пожалуйста, приложить скрин полученной страницы, пожалуйста?)

2021-05-08 11:39 UTC, tomasedk commented on src/components/button/index.tsx
> +    type?: 'button' | 'submit' | undefined | 'reset'
Предлагаю вынести типы кнопок в енам
```typescript
enum EButtonType {
   PRIMARY, // основной цвет
   SECONDARY, // дополнительный
   ERROR, // опасное действие
}
```
и каждая из них будет отличаться только цветом. В твоем случае не совсем ясно, чем будет отличаться button от submit :)

Так же когда мы указываем, что пропса опциональная `(type?)`, то `| undefined` уже указывать не нужно :)

2021-05-08 11:39 UTC, tomasedk commented on src/components/button/index.tsx
> +        <div key={textButton}>
не подскажешь, зачем эта обертка дивом?)

2021-05-08 11:39 UTC, tomasedk commented on src/components/button/styles.css
> +button {
предлагаю такие дефолтные стили для всех кнопок:
```css
.button {
    padding: xxx;
    font-size: xxx;
    cursor: pointer;
    outline: none;
    width: xxx;

    &:active { //  написано на less, но надо сделать под наш препроцессор
        background-color: @color-primary-light;
    }
}
```

2021-05-08 11:39 UTC, tomasedk commented on src/components/button/styles.css
> +.login-signin-form__button {
как насчет того, чтобы не переименовать все файлы стилей на соотв-ие функциональные области, чтобы упросить поиск по проекту? Типа:
```
common.css // тут будут лежать стили для общих комопнент типа кнопок, инпутов и тд.
login.css // здесь стили чисто для страницы логина
```

И кастомные стили для кнопки, кмк, можно было бы перенести в стили логин-формы :)

2021-05-08 11:39 UTC, tomasedk commented on src/components/form/styles.css
> +.form{
надо бы прогнать все файлы через prettier, чтобы он поправил все отступы и прочее.)

2021-05-08 11:39 UTC, tomasedk commented on src/components/form/index.tsx
> +export function Form(classForm: string, arrayInputs: JSX.Element[], arrayButtons: JSX.Element[]) {
давай писать компоненты с указанием типизации как самого компонента, так и пропов?) и еще круто было бы добавлять jsDoc'и :)
Типа того:

```typescript


/**
 * Пропы, такие-то такие-то.
 *
 * @param classForm описание пропа.
 * @param arrayInputs описание пропа.
 * @param arrayButtons описание пропа.
 */
export type TFormProps = {
    classForm: string;
    arrayInputs: JSX.Element[];
    arrayButtons: JSX.Element[];
};

export const Form: React.FC<TFormProps> = ({classForm, arrayInputs, arrayButtons}) => { }
```

2021-05-08 11:39 UTC, tomasedk commented on src/consts/index.tsx
> +export const consts = {
я так понял, это текстовки, верно? Мб файл так и назовем типа translations.ts. и Константу, соотв-но, так же :)

2021-05-08 11:39 UTC, tomasedk commented on src/pages/signin/index.tsx
> +        Input(consts.signinPage.email, 'text', 'email', consts.error.errorTextEmptyField),
надо бы, думаю, переписать компоненты именно на функциональные компоненты, а не на функции, чтобы мы могли их так использовать:
```tsx
<Input(
    label={consts.signinPage.email}
    type={EInputType.TEXT}
    name={email}
    textError={consts.error.errorTextEmptyField}
/>
```

2021-05-11 19:46 UTC, SashaMalova commented on src/components/button/index.tsx
> +    type?: 'button' | 'submit' | undefined | 'reset'
кнопки же не только цветом отличаться будут, но и размером, будем выносить размеры тоже в енам отдельный. я думала, и цвет и размер будет buttonClass регулировать

2021-05-11 19:46 UTC, SashaMalova commented on src/components/button/index.tsx
> +        <div key={textButton}>
убрала

2021-05-11 20:06 UTC, SashaMalova commented on src/components/button/styles.css
> +button {
font-size у нас разный для разных кнопок и фона нет. добавила button:hover и button: active
button {
    border: none;
    font: inherit;
    color: inherit;
    background-color: transparent;
    cursor: pointer;
    padding-right: 10px;
    padding-left: 10px;
}

button:active, button:hover {
    text-shadow: var(--color-games-title) 2px 2px 0, var(--color-games-title) -2px -2px 0,
    var(--color-games-title) -2px 2px 0, var(--color-games-title) 2px -2px 0;
 }

2021-05-11 20:23 UTC, SashaMalova commented on src/components/button/styles.css
> +.login-signin-form__button {
файлы переименовала, кастомные стили перенесла

2021-05-11 21:36 UTC, SashaMalova commented on src/components/form/index.tsx
> +export function Form(classForm: string, arrayInputs: JSX.Element[], arrayButtons: JSX.Element[]) {
Переписала

2021-05-11 21:42 UTC, SashaMalova commented on src/consts/index.tsx
> +export const consts = {
поменяла

2021-05-11 21:42 UTC, SashaMalova commented on src/pages/signin/index.tsx
> +        Input(consts.signinPage.email, 'text', 'email', consts.error.errorTextEmptyField),
Переписала

2021-05-11 21:42 UTC, SashaMalova commented on src/components/form/styles.css
> +.form{
Вроде всё поправилось

2021-05-11 21:49 UTC, SashaMalova commented
![2021-05-12_00-45-38](https://user-images.githubusercontent.com/78325304/117889244-dfe6b780-b2bb-11eb-9f9e-9fae40541c18.png)
![2021-05-12_00-34-01](https://user-images.githubusercontent.com/78325304/117889248-e117e480-b2bb-11eb-9456-478d18bbfaed.png)

2021-05-13 09:41 UTC, tomasedk commented on src/components/button/index.tsx
> +import * as React from 'react';
Вообще предлагаю взять код для кнопки прямо с главы TypeScript в React. Как по мне, там довольно хорошо все описано :)

2021-05-13 09:41 UTC, tomasedk commented on package.json
> +    "file-loader": "^6.2.0",
а зачем эта зависимость?)

2021-05-13 09:41 UTC, tomasedk commented on src/assets/html/index.html
> +<div id='app' class='container'></div>
все контейнеры надо бы навешивать уже в рамках инстанса реакта :)

2021-05-13 09:41 UTC, tomasedk commented on src/components/input/index.tsx
> +
лишний \n закрался :)

2021-05-13 09:41 UTC, tomasedk commented on src/components/input/index.tsx
> +import * as React from 'react';
давай попробуем переписать этот общий компонент с оглядкой на пример из теории ЯПрактикума, где наследуются типы стандартного инпута?)

2021-05-13 09:41 UTC, tomasedk commented on src/pages/login/index.tsx
> +        Input({
а здесь в таком формате (< Input />) не получится написать?)

2021-05-13 09:41 UTC, tomasedk commented on src/pages/login/login.css
> +.backgroundBack{
что-то здесь тоже преттиром надо пройтись по файлу.) можешь все файлы прогнать, плиз?

2021-05-13 09:41 UTC, tomasedk commented on src/components/button/index.tsx
> +    buttonClass: string;
не смог ответить на твой комментарий насчет цвета и размера, так как тот файл уже outdated, поэтому напишу здесь :)

Да, задать отдельным енамом еще размер надо, если кнопки будут отличаться и по этому параметру.)

2021-05-13 11:46 UTC, SashaMalova commented on package.json
> +    "file-loader": "^6.2.0",
Я так поняла, что картинки шрифты должны обрабатываться url-loader, но сейчас он выдает ошибку и запрашивается file-loader.
![2021-05-13_14-39-00](https://user-images.githubusercontent.com/78325304/118120976-710f7880-b3f9-11eb-99fd-5f81808cbf1d.png)

2021-05-13 22:07 UTC, SashaMalova commented on src/components/button/index.tsx
> +import * as React from 'react';
Переписала

2021-05-13 22:39 UTC, SashaMalova commented on src/assets/html/index.html
> +<div id='app' class='container'></div>
Поправила

2021-05-13 22:44 UTC, SashaMalova commented on src/components/input/index.tsx
> +
убрала

2021-05-13 22:45 UTC, SashaMalova commented on src/components/input/index.tsx
> +import * as React from 'react';
не нашла какой пример ты имеешь ввиду, но переписала по аналогии с кнопкой

2021-05-13 22:45 UTC, SashaMalova commented on src/pages/login/index.tsx
> +        Input({
Получилось

2021-05-13 22:45 UTC, SashaMalova commented on src/pages/login/login.css
> +.backgroundBack{
Прошлась во всем src

2021-05-13 22:46 UTC, SashaMalova commented on src/components/button/index.tsx
> +    buttonClass: string;
Добавила enumы

2021-05-14 10:53 UTC, tomasedk approved these changes

2021-05-14 10:53 UTC, tomasedk commented on package.json
> +    "file-loader": "^6.2.0",
Хм, такое возможно, да. Только тогда надо закинуть это в дев-зависимости, так как этот пакет нужен только на этапе сборки :)
```npm install file-loader --save-dev```

2021-05-14 10:53 UTC, tomasedk commented on src/components/button/index.tsx
> +import * as React from 'react';
супер!)

2021-05-14 10:53 UTC, tomasedk commented on src/components/input/index.tsx
> +import * as React from 'react';
да, там не было примера прям с инпутом. Имел в виду кнопку :)

2021-05-14 10:56 UTC, tomasedk approved these changes

2021-05-14 14:34 UTC, bercly0b commented on package.json
> +    "file-loader": "^6.2.0",
да, нужно в дев зависимости переложить

2021-05-14 14:36 UTC, bercly0b commented on src/components/button/button.css
> +button {
давайте не будем использовать селектор по тегу? это противоречит методологии бэма, ну и такой селектор очень легко может применится туда, где это не ожидается

2021-05-14 14:44 UTC, bercly0b commented on src/components/button/index.tsx
> +function getButtonClass(buttonColour: EButtonColour, buttonType: EButtonType): string {
если мы пытаемся придерживаться бэма, то:
с `buttonColour` - ок, только `color`, а не `colour`)
c `buttonType` 
  - error__button - не ок, должен получится модификатор вида button__type-error
  -  login-signin-form__button - не ок, в бэме это называется микс. это когда к существующему блоку добавляется еще какой то класс, в данном случае это блок button, но в то же время миксуется класс login-signin-form__button (тоесть элемент формы). микс нужно передавать снаружи. только button внутри себя генерирует свой класснейм на основе пропсов (цвет тип размер) и так же принимает пропс className, который просто добавляется к сгенерированной строке.

таким образом для компонента `<Button buttonColour="primary" buttonType="error" className="login-signin-form__button">` должен получится класс `button button__type-error button__color-primary login-signin-form__button`

для того что бы не генерировать такие длинные строки руками - можно затащить какую нибудь библиотечку. если  не получится найти самим можно написать мне, я подскажу

2021-05-14 14:46 UTC, bercly0b commented on src/components/button/index.tsx
> +export const Button: Props = ({text, buttonColour, buttonType, ...otherProps}: TButtonProps) => {
`buttonColor` и `buttonType` я бы переименовал в `color` и `type` 
и так понятно что это пропсы кнопки и имеют отношение к кнопке а не к чему то другому)

2021-05-14 14:48 UTC, bercly0b commented on src/components/input/index.tsx
> +            <span className="input__error-text">{textError}</span>
есть textError нет, то отрендерится пустой спан.
давай сперва проверим
`{textError && <span className="input__error-text">{textError}</span>}`

2021-05-14 14:49 UTC, bercly0b commented on src/pages/login/index.tsx
> +            type={'text'}
строки можно передавать без `{}`

2021-05-14 14:52 UTC, bercly0b commented on src/pages/login/index.tsx
> +                    arrayInputs={arrayInputs}
я бы лучше передавал инпуты и кнопки как `children`? 
так читается лучше. 
но это не критично.

2021-05-14 14:52 UTC, bercly0b requested changes
пройдись по комментам пож

2021-05-14 19:56 UTC, SashaMalova commented on package.json
> +    "file-loader": "^6.2.0",
сделано

2021-05-14 20:13 UTC, SashaMalova commented on src/components/button/button.css
> +button {
Исправила

2021-05-14 20:54 UTC, SashaMalova commented on src/components/button/index.tsx
> +export const Button: Props = ({text, buttonColour, buttonType, ...otherProps}: TButtonProps) => {
Мы добавляем к нашим пропсам  ButtonHTMLAttributes. Получится дублирование пропсов color и type, они входят в атрибуты кнопки по умолчанию.

2021-05-14 21:23 UTC, SashaMalova commented on src/components/input/index.tsx
> +            <span className="input__error-text">{textError}</span>
Да пустой, поправила стили у него, чтоб отступы сохранялись

2021-05-14 21:27 UTC, SashaMalova commented on src/pages/login/index.tsx
> +            type={'text'}
Поправила

2021-05-14 21:44 UTC, SashaMalova commented on src/pages/login/index.tsx
> +                    arrayInputs={arrayInputs}
Получается не очень удобно, так как инпуты и кнопки не подряд, а разнесены в форме по разным местам. Ну или я не совсем поняла, как это красиво сделать в таком случае)

2021-05-14 21:46 UTC, SashaMalova commented on src/components/button/index.tsx
> +function getButtonClass(buttonColour: EButtonColour, buttonType: EButtonType): string {
поправила

2021-05-16 06:55 UTC, bercly0b approved these changes

2021-05-17 22:58 UTC, merged