S8 t11 theme
odessa-yandex-praktikum/crazy-bomber pull request #30
Opened 2021-07-10 23:04 UTC by SashaMalova

Подключен sequelize. Добавлены PostrySQL, Docker-compose. Созданы модели таблиц для работы с темами, Ручки по работе с темизацией. Добавлен элемент на странице профиля для изменения темы. Тема отвечает за изменение цвета форм. При повторном входе подгружается сохраненная тема пользователя.

2021-07-10 23:05 UTC, SashaMalova commented
![2021-07-11_01-42-35](https://user-images.githubusercontent.com/78325304/125178313-57699200-e1ec-11eb-8823-fafa676e4ff1.png)
![2021-07-11_01-44-08](https://user-images.githubusercontent.com/78325304/125178320-618b9080-e1ec-11eb-81fd-6e1ec3ddcbe6.png)
![2021-07-11_01-43-02](https://user-images.githubusercontent.com/78325304/125178324-64868100-e1ec-11eb-83a9-56bd32e1c44d.png)

2021-07-12 19:10 UTC, SashaMalova commented
![](https://github.trello.services/images/mini-trello-icon.png) [Настроить PostgreSQL в проекте (Docker + запуск проекта локально) и проверить, что CRUD работает](https://trello.com/c/2XCYQiZY/11-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B8%D1%82%D1%8C-postgresql-%D0%B2-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B5-docker-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0-%D0%BB%D0%BE%D0%BA%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE-%D0%B8-%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%B8%D1%82%D1%8C-%D1%87%D1%82%D0%BE-crud-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82)

2021-07-13 18:04 UTC, lalalilulu commented on db/create.sql
> +INSERT INTO site_theme (theme) VALUES ('Dark'), ('Light');
по идее при старте сервера создаются нужные базы, когда добавляем модели - нужно продумать, как предзаполнять базу нужными темами

2021-07-13 18:07 UTC, lalalilulu commented on src/store/actions/userActions.ts
> -            .then((r: Response) => r.json())
точно можно убрать ? https://developer.mozilla.org/en-US/docs/Web/API/Response/json

2021-07-13 18:08 UTC, lalalilulu approved these changes
привет! посмотри плиз комментарии, они не критичные. сегодня запускали приложение с базой вместе

2021-07-14 15:26 UTC, SashaMalova commented
![](https://github.trello.services/images/mini-trello-icon.png) [Настроить PostgreSQL в проекте (Docker + запуск проекта локально) и проверить, что CRUD работает](https://trello.com/c/2XCYQiZY/11-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B8%D1%82%D1%8C-postgresql-%D0%B2-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B5-docker-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0-%D0%BB%D0%BE%D0%BA%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE-%D0%B8-%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%B8%D1%82%D1%8C-%D1%87%D1%82%D0%BE-crud-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82)

2021-07-14 15:27 UTC, SashaMalova commented on db/create.sql
> +INSERT INTO site_theme (theme) VALUES ('Dark'), ('Light');
Сделала, таблица предзаполняется

2021-07-14 15:27 UTC, SashaMalova commented on src/store/actions/userActions.ts
> -            .then((r: Response) => r.json())
Да, я перенесла в user-api где нужно

2021-07-14 18:03 UTC, tomasedk commented
Надо прогнать весь ПР через преттиер

2021-07-14 18:07 UTC, tomasedk commented
https://github.com/odessa-yandex-praktikum/crazy-bomber/pull/30/files#diff-a4c65ede64197e1a112899a68bf994485b889c4b143198bac4af53425b38406f этот сервер уже не нужен, надо брать скомпиленный из dist'а

2021-07-14 18:15 UTC, tomasedk commented on .eslintrc.js
> +        project: 'tsconfig.eslint.json',
а зачем это, если уже есть тсконфиг?

2021-07-14 18:15 UTC, tomasedk commented on src/server/controllers/theme.ts
> +export const createSiteTheme = async (): Promise<void> => {
это не похоже на хэндлер, надо вынести в другое место

2021-07-14 18:15 UTC, tomasedk commented on src/components/theme-switcher/index.tsx
> +export const updateTheme = (theme: string) => {
мы же договорились о другом механизме работы темизации. Это не будет работать с ssr-ом

2021-07-14 18:15 UTC, tomasedk commented on src/components/theme-switcher/index.tsx
> +    console.log(id);
убрать артефакты разработки

2021-07-14 18:15 UTC, tomasedk commented on Dockerfile
> +COPY server.js server.js
этот сервер уже не нужен. У нас есть свой в dist'е

2021-07-14 18:15 UTC, tomasedk commented on src/server/server.ts
> +(async function () {
почему запуск сервера выше хэндлеров? мы же по другому делали в ветке test и все работало. + в итоге не ясно, зачем самовызывающаясяя функция

2021-07-14 18:15 UTC, tomasedk commented on src/server/server.ts
> +import {Express, Router} from 'express';
выше уже есть импорт экспресса

2021-07-14 18:15 UTC, tomasedk commented on src/services/api/theme-api.ts
> +export function getUserTheme(userID: number): Promise<any> {
надо описать каждый хэндлер jsDoc'ом

2021-07-14 18:15 UTC, tomasedk commented on src/server/controllers/theme.ts
> +        res.send('ok');
зачем это возращать, если можно просто 200 отправить в коде ответа?

2021-07-14 18:15 UTC, tomasedk commented on src/services/api/user-api.ts
> +                    getThemeById(ThemeId.theme_id).then((Theme: any) => {
надо убрать везде any и добавить типизацию

2021-07-14 18:15 UTC, tomasedk commented on src/store/reducers/userReducer.ts
> +const currentUser: Nullable<User> = null; // TODO. Добавить middleware на сервере для проверки пользователя.
все же пока пусть будет {}, иначе просто не будет давать зайти в игру

2021-07-14 18:23 UTC, tomasedk commented
падает запрос:
![image](https://user-images.githubusercontent.com/37691223/125673022-3ce1227a-1818-450c-96de-2b49cda859a7.png)

2021-07-14 18:28 UTC, SashaMalova commented on src/components/theme-switcher/index.tsx
> +export const updateTheme = (theme: string) => {
оно же уже работает?

2021-07-14 18:30 UTC, tomasedk commented on src/components/theme-switcher/index.tsx
> +export const updateTheme = (theme: string) => {
нет, ssr не может обращаться к document, поэтому мы решили переделать на redux вчера же еще

2021-07-14 18:34 UTC, SashaMalova commented
> падает запрос:
> ![image](https://user-images.githubusercontent.com/37691223/125673022-3ce1227a-1818-450c-96de-2b49cda859a7.png)

Это потому что записи в таблице ещё нет. он и возвращает что не нашел

2021-07-14 18:35 UTC, tomasedk commented
а нельзя как-то по дефолту инсертить значения?

2021-07-14 18:45 UTC, lalalilulu commented
> а нельзя как-то по дефолту инсертить значения?
по идее можно это добавить при определении темы - если тема не найдена - дефолтную сохранять в базу; сейчас ты можешь в настройках пользователя поменять тему, тогда за твоим юзером сохранится тема и ошибки не будет

2021-07-14 18:50 UTC, SashaMalova commented on src/server/controllers/theme.ts
> +export const createSiteTheme = async (): Promise<void> => {
сделано

2021-07-14 18:55 UTC, SashaMalova commented on src/components/theme-switcher/index.tsx
> +    console.log(id);
сделано

2021-07-14 18:56 UTC, SashaMalova commented on Dockerfile
> +COPY server.js server.js
yes

2021-07-14 18:56 UTC, SashaMalova commented on .eslintrc.js
> +        project: 'tsconfig.eslint.json',
вернула

2021-07-14 19:03 UTC, SashaMalova commented on src/services/api/theme-api.ts
> +export function getUserTheme(userID: number): Promise<any> {
Это необходимо? Просто мы вроде торопимся или уже нет?

2021-07-14 19:05 UTC, SashaMalova commented on src/store/reducers/userReducer.ts
> +const currentUser: Nullable<User> = null; // TODO. Добавить middleware на сервере для проверки пользователя.
Поменяла

2021-07-14 19:08 UTC, SashaMalova commented on src/server/server.ts
> +import {Express, Router} from 'express';
Это интерфейс

2021-07-14 19:19 UTC, SashaMalova commented on src/server/controllers/theme.ts
> +        res.send('ok');
Поменяла

2021-07-14 19:24 UTC, SashaMalova commented on src/services/api/user-api.ts
> +                    getThemeById(ThemeId.theme_id).then((Theme: any) => {
убрала-добавила

2021-07-15 09:10 UTC, SashaMalova commented on src/components/theme-switcher/index.tsx
> +export const updateTheme = (theme: string) => {
сделала через redux

2021-07-16 13:19 UTC, bercly0b commented on src/store/actions/userActions.ts
> +                        getThemeById(ThemeId.theme_id).then(
можно какую то функцию сделать для объединения цепочки `getUserTheme.then.getThemeById` что бы переиспользовать

2021-07-16 13:22 UTC, bercly0b commented on src/services/api/theme-api.ts
> +export function getUserTheme(userID: number): Promise<{}> {
не обратили внимание что почти у всех запросов одинаковый набор парамтров. потом одинаковое `.then((r: Response) => r.json())`

можно было бы сделать какую то базовую сущность для походов по сети. которая будет принимать урл и параметры, если параметров нет - подставлять дефолтные. делать парсинг ответов и приведение ошибок к единому формату.

и тогда кода тут будет значительно меньше)

2021-07-16 13:24 UTC, bercly0b commented on src/pages/profile/index.tsx
> +    let {theme} = useTypedSelector((state) => state.user);
`let {theme = 'GREY'} = useTypedSelector((state) => state.user);`

2021-07-16 13:25 UTC, bercly0b commented on src/pages/login/index.tsx
> +    let {theme} = useTypedSelector((state) => state.user);
let {theme = 'GREY'} = useTypedSelector((state) => state.user);

2021-07-16 13:26 UTC, bercly0b requested changes
много дублирования кода.. основное описал в комментах

2021-07-20 18:31 UTC, SashaMalova commented on src/pages/login/index.tsx
> +    let {theme} = useTypedSelector((state) => state.user);
Поправила

2021-07-20 18:31 UTC, SashaMalova commented on src/pages/profile/index.tsx
> +    let {theme} = useTypedSelector((state) => state.user);
Поправила

2021-07-20 19:30 UTC, SashaMalova commented on src/services/api/theme-api.ts
> +export function getUserTheme(userID: number): Promise<{}> {
Сделала вспомогательную функцию для get запроса

2021-07-21 20:29 UTC, SashaMalova commented on src/store/actions/userActions.ts
> +                        getThemeById(ThemeId.theme_id).then(
Сделала

2021-07-23 09:46 UTC, lalalilulu approved these changes

2021-07-23 18:32 UTC, SashaMalova commented on src/services/api/theme-api.ts
> +export function getUserTheme(userID: number): Promise<any> {
Написала

2021-07-29 09:17 UTC, lalalilulu commented
@SashaMalova все поправлено, может вмержим в основную ветку спринта?

2021-08-01 10:53 UTC, tomasedk commented on src/components/form/index.tsx
> +        <div className={`form  ${classForm}`}>
лишний пробел

2021-08-01 10:53 UTC, tomasedk commented on src/store/actions/userActions.ts
> +            .then(async (data: UserData) => {
зачем здесь async?
![image](https://user-images.githubusercontent.com/37691223/127765475-e7a4210d-3264-482e-88b4-33df5d68c1c1.png)

2021-08-01 10:53 UTC, tomasedk commented on tsconfig.eslint.json
> +{
а зачем этот файл нужен?

2021-08-01 10:53 UTC, tomasedk commented on src/components/theme-switcher/index.tsx
> +        dispatch(userActions.changeTheme(e?.target?.value, id));
а зачем тут диспатчить, если это сам userActions.changeTheme должен делать?

2021-08-01 10:53 UTC, tomasedk commented on src/components/theme-switcher/index.tsx
> +import {useCallback} from 'react';
дублирование импорта реакта

2021-08-01 10:53 UTC, tomasedk commented on src/index.client.tsx
> +export const {store, history} = configureStore(window.__INITIAL_STATE__);
а зачем это экспортить?

2021-08-01 20:32 UTC, SashaMalova commented on src/store/actions/userActions.ts
> +            .then(async (data: UserData) => {
Поправила

2021-08-01 20:32 UTC, SashaMalova commented on src/components/form/index.tsx
> +        <div className={`form  ${classForm}`}>
Поправила

2021-08-01 20:32 UTC, SashaMalova commented on tsconfig.eslint.json
> +{
убрала

2021-08-01 20:50 UTC, SashaMalova commented on src/components/theme-switcher/index.tsx
> +        dispatch(userActions.changeTheme(e?.target?.value, id));
userActions.changeTheme возвращает Dispatch, так же как и другие actions: getUser, register, login, changeProfile,   changePassword, changeAvatar, logout,

2021-08-01 20:51 UTC, SashaMalova commented on src/components/theme-switcher/index.tsx
> +import {useCallback} from 'react';
Поправила

2021-08-01 20:56 UTC, SashaMalova commented on src/index.client.tsx
> +export const {store, history} = configureStore(window.__INITIAL_STATE__);
убрала

2021-08-01 21:15 UTC, merged