S5T19: Добавлен роутинг в проект
odessa-yandex-praktikum/crazy-bomber pull request #5
Opened 2021-05-08 13:46 UTC by tomasedk

2021-05-08 17:20 UTC, lalalilulu commented on src/index.tsx
> +ReactDOM.render(
супер! я тоже думаю, что нужно использовать BrowserRouter

2021-05-08 17:38 UTC, lalalilulu requested changes
Все хорошо! Оставила несколько комментариев с возможными улучшениями

2021-05-08 17:38 UTC, lalalilulu commented on src/Pages/Logon.tsx
> +import * as React from 'react';
не уверена, что нужно делать новые компоненты - у нас уже есть те, что сделала Саша и я

2021-05-08 17:38 UTC, lalalilulu commented on src/App.tsx
> +                    <Route path="/login" component={Login} />
если нет exact, то можно открыть логин и по урлу '/logingghh'
 и я бы добавила redirect -  <Redirect from='*' to='/'/> - если пользователь что-то неепонятное наберет, то попадет на главную старницу

2021-05-08 17:38 UTC, lalalilulu commented on src/App.tsx
> +import {Link} from 'react-router-dom';
не обязательно напрямую импортить все - не все понадобится сразу) есть полезная штука - ленивые вычисления, то есть мы импортим то, что пользователю нужно сразу, а остальное через функцию lazy 
пример: const Logon= lazy(() => import("./Pages/Logon"));

2021-05-08 17:38 UTC, lalalilulu commented on src/index.tsx
> +        <App />
возможна задержка данных при получении, отрисовки страницы, поэтому можно добавить на этот случай компонент <Suspense> Тут можно почитать подробнее https://ru.reactjs.org/docs/concurrent-mode-suspense.html

2021-05-08 17:38 UTC, lalalilulu commented on src/App.tsx
> +                    <Route path="/" exact component={Main} />
И очень важный момент - сейчас никак не учтено, что не все пути доступны для незалогиненого пользователя - например, если я не вошла в систему, то я не должна иметь возможность открыть Profile. В таких случаях применяют HOC  PrivateRoute Component. Тогда доступ к компоненте имеет только залогиненный пользователь иначе - редирект на логин. Тут можно подробнее почитать - https://medium.com/@tomlarge/private-routes-with-react-router-dom-28e9f40c7146

2021-05-09 07:38 UTC, tomasedk commented on src/Pages/Logon.tsx
> +import * as React from 'react';
Ты про логин и тд?)
Я их просто добавил как заглушки. Потом, когда будут решаться конфликты, это все поправить надо будет :)

2021-05-09 07:48 UTC, tomasedk commented on src/App.tsx
> +                    <Route path="/login" component={Login} />
И правда! что-то я об этом не подумал, поправлю :)

2021-05-10 06:52 UTC, tomasedk commented on src/App.tsx
> +                    <Route path="/login" component={Login} />
Добавил exact в такие роуты, а <Route path="/" exact component={Main} /> добавил в низ списка роутов, чтобы была дефолтной страницей

2021-05-10 06:53 UTC, tomasedk commented on src/App.tsx
> +import {Link} from 'react-router-dom';
Я думал потом это добавить, но ты же права, лучше добавить сразу. Сделал :)

2021-05-10 06:55 UTC, tomasedk commented on src/index.tsx
> +        <App />
Спасибо, добавил fallback-страницу!)

2021-05-10 06:55 UTC, tomasedk commented on src/App.tsx
> +                    <Route path="/" exact component={Main} />
Точно, я совсем об это забыл! Добавил приватные роуты, и для примера странцу Leaderboard. Так же дальше надо будет продумать логику проверки доступа :)

2021-05-10 11:23 UTC, lalalilulu approved these changes
нужные изменения внесены

2021-05-11 16:06 UTC, bercly0b commented on src/App.tsx
> +                <ul>
можно было навигацию в отдельный компонент вынести. но пока не критично

2021-05-11 16:08 UTC, bercly0b approved these changes

2021-05-11 16:08 UTC, merged