S5T5: Реализовать состояние начала игры
odessa-yandex-praktikum/crazy-bomber pull request #7
Opened 2021-05-11 14:30 UTC by lalalilulu

Итоговый скрин: 
![game-startStage](https://user-images.githubusercontent.com/39400036/117832621-4f3db680-b27e-11eb-9c97-573d13f1ab1c.JPG)
Добавлены основные игровые сущности - самолет и здания (пока без методов - атаковать, изменение отрисовки после попадания)

2021-05-11 14:30 UTC, lalalilulu commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать состояние начала игры](https://trello.com/c/yUpejpYO/5-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B5-%D0%BD%D0%B0%D1%87%D0%B0%D0%BB%D0%B0-%D0%B8%D0%B3%D1%80%D1%8B)

2021-05-13 09:42 UTC, tomasedk commented on src/consts/index.tsx
> +enum BUILDING {
для енамов лучше завести отдельный файл enums.ts. :)

а этот файл лучше перевести в говорящее название что-то типа translations.ts
а все остальные константы можно закинуть в consts.ts :)

2021-05-13 09:42 UTC, tomasedk commented on src/game/Models.ts
> +        this.x = x;
в тс-е есть короткая запись для таких конструкций: https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties :)

2021-05-13 09:42 UTC, tomasedk commented on src/game/Models.ts
> +    x: number;
когда пишем в ООП стиле думаю, лучше придерживаться правила "явное лучше неявного". В этому случае запись
```typescript
x: number;
```
трактуется тс-ом как:
```typescript
public x: number;
```

так вот предлагаю у всем методов и полей классов (не только Coordinate) явно указывать модификаторы доступа public, protected, private :)

2021-05-13 09:42 UTC, tomasedk commented on src/index.tsx
> +ReactDOM.render(<GameBoard />, document.getElementById('app'));
уже можно создавать новую пейджу и закидывать ее в роутинг, так как влился ПР по роуту :)

2021-05-13 09:42 UTC, tomasedk commented on src/pages/gameboard/gameboard.css
> +.gameScore {
давай постараемся придерживаться БЕМа, мб?)

2021-05-13 09:42 UTC, tomasedk commented on src/game/Models.ts
> +    type: any;
а почему any?) нельзя разве сразу при создании экземпляра прокидывать нужный BUILDING?)

2021-05-13 09:42 UTC, tomasedk commented on src/consts/index.tsx
> +enum BUILDING {
еще есть такое соглашение, что enum'ы начинаются с  Е..., интерфейсы с I..., а типы с T... Чтобы по неймингу можно было сразу понять, что это за сущность.)

2021-05-13 09:42 UTC, tomasedk commented on src/pages/gameboard/index.tsx
> +    const [score, setScore] = useState('0000000');
думаю, score все же в стейте (а потом в ридакс-сторе) надо бы хранить в виде number, но при отображении уже добавлять какой-нибудь простой утилкой лидирующие нули. Это облегчит нам калькуляцию значений.)

2021-05-13 09:42 UTC, tomasedk commented on src/pages/gameboard/index.tsx
> +    function drawInitialStage(canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D) {
предлагаю писать ф-ии в стрелочном виде, чтобы ненароком не потерять контекст, если что :)

2021-05-14 10:29 UTC, lalalilulu commented on src/consts/index.tsx
> +enum BUILDING {
перенесла enum в специальный файл

2021-05-14 10:30 UTC, lalalilulu commented on src/game/Models.ts
> +        this.x = x;
изменен конструктор

2021-05-14 10:30 UTC, lalalilulu commented on src/game/Models.ts
> +    x: number;
добавлены модификаторы доступа

2021-05-14 10:31 UTC, lalalilulu commented on src/index.tsx
> +ReactDOM.render(<GameBoard />, document.getElementById('app'));
добавлен роут

2021-05-14 10:31 UTC, lalalilulu commented on src/pages/gameboard/gameboard.css
> +.gameScore {
стили переименованы

2021-05-14 10:31 UTC, lalalilulu commented on src/game/Models.ts
> +    type: any;
изменен тип

2021-05-14 10:32 UTC, lalalilulu commented on src/pages/gameboard/index.tsx
> +    const [score, setScore] = useState('0000000');
изменено - функция есть в другом пул-реквесте, поэтому времено дописана в этом же файле, потом будет удалена

2021-05-14 10:32 UTC, lalalilulu commented on src/pages/gameboard/index.tsx
> +    function drawInitialStage(canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D) {
все функции сделаны стрелочными

2021-05-14 13:50 UTC, tomasedk approved these changes
Круто!)

2021-05-14 14:26 UTC, bercly0b commented on src/Pages/gameboard/index.tsx
> +    const drawInitialStage = (canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D) => {
кажется эта функция только работает с канвасом и особо не имеет отношения к компоненту.
давай вынесем ее куда нибудь наружу компонента?
и `drawBuilding` тоже
и `convertScoreToString`

для отрисовки игровых деталей можно создать отдельный класс и тут дергать его методы

2021-05-14 14:29 UTC, bercly0b commented on src/consts/enums.tsx
> +enum EBuilding {
лучше именовать файлы не по типам данных которые в нем лежат, а по тому к чему эти данные относятся.
с ростом проекта, если все енамы складывать в один файл тут образуется большая свалка.
я бы навал этот файл `game.types.ts` или что нибудь в таком стиле
и не `tsx` - это расширение для `jsx` разметки. где не используется реакт это просто `ts`

2021-05-14 14:31 UTC, bercly0b commented on src/pages/gameboard/index.tsx
> +import * as React from 'react';
чем этот файл отличается от `src/Pages/gameboard/index.tsx` ?

2021-05-14 14:32 UTC, bercly0b requested changes
пройдись пож по комментам.
и все `png` файлы нужно прогнать через оптимизатор какой нибудь.

2021-05-14 14:56 UTC, lalalilulu commented on src/pages/gameboard/index.tsx
> +import * as React from 'react';
вероятно, это данные предыдущего коммита

2021-05-14 14:56 UTC, lalalilulu commented on src/consts/enums.tsx
> +enum EBuilding {
исправлено

2021-05-14 14:56 UTC, lalalilulu commented on src/Pages/gameboard/index.tsx
> +    const drawInitialStage = (canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D) => {
вынесены

2021-05-16 06:51 UTC, bercly0b approved these changes

2021-05-16 06:51 UTC, merged