S5t60: Сделать компонент для навигации
odessa-yandex-praktikum/crazy-bomber pull request #9
Opened 2021-05-18 19:12 UTC by lalalilulu

Сделан компонент для навигации между страницами.
В компонент добавлен Link для перехода между страницами. 
Важно! На страницы Логина и Регистрации навигация не добавлена, так как основые пути являются прайвит роутами (лидерборд, форум, игра)
Cтраницы приложения: 
![main-page](https://user-images.githubusercontent.com/39400036/118709726-06f63980-b826-11eb-86c0-cc61922c9672.JPG)
![profile-page](https://user-images.githubusercontent.com/39400036/118709735-09f12a00-b826-11eb-9240-95a4c6b8d70d.JPG)
![signin-page](https://user-images.githubusercontent.com/39400036/118709745-0b225700-b826-11eb-8c42-b572c4590116.JPG)
![leaderboard-page](https://user-images.githubusercontent.com/39400036/118709755-0f4e7480-b826-11eb-81f4-b76000c6817a.JPG)
![login-page](https://user-images.githubusercontent.com/39400036/118709763-12496500-b826-11eb-99ca-a22e6db29ff3.JPG)
![forum-page](https://user-images.githubusercontent.com/39400036/118709774-15dcec00-b826-11eb-9fbd-6cdbecf3d27e.JPG)
![forum-topic-page](https://user-images.githubusercontent.com/39400036/118709781-17a6af80-b826-11eb-9e0c-fd86367e0593.JPG)
![gameboard-page](https://user-images.githubusercontent.com/39400036/118709787-1b3a3680-b826-11eb-90e9-3c9b63e40dd0.JPG)

2021-05-18 19:14 UTC, lalalilulu commented
![](https://github.trello.services/images/mini-trello-icon.png) [Сделать компонент для навигации](https://trello.com/c/85DvAADw/60-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82-%D0%B4%D0%BB%D1%8F-%D0%BD%D0%B0%D0%B2%D0%B8%D0%B3%D0%B0%D1%86%D0%B8%D0%B8)

2021-05-20 11:50 UTC, SashaMalova approved these changes

2021-05-20 14:49 UTC, bercly0b commented on src/components/navi/index.tsx
> +export const Navi: React.FC<TNaviProps> = ({arrayNaviItems}: TNaviProps) => {
я бы не стал экономить символы и назвал `Navigation`

2021-05-20 14:50 UTC, bercly0b commented on src/components/navi/index.tsx
> + * @param arrayNaviItems массив элементов навигации
у нас же тайпскрипт. нам точно нужно еще и `jsdoc` писать?) вроде по неймингу понятно что это)

2021-05-20 14:53 UTC, bercly0b commented on src/pages/forum/index.tsx
> +        new TNaviItem(navLinkStart, createNaviPath(navLinkStart)),
можно было бы генерацию этих элементов перенести внутрь компонента навигации. а с наружи ему говорить только какие элменты нужно показывать.
тогда вся логика по навигации будет находится внутри компонента, а не будет размазана по разным местам

2021-05-20 14:55 UTC, bercly0b commented on src/pages/forum/index.tsx
> +        new TNaviItem(navLinkStart, createNaviPath(navLinkStart)),
и с конструктором не очень хорошая идея, потому что в текущей реализации на каждый ререндер будут создавать новые инстансы (с новыми ссылками на них) и компонент навигации будет считать это за новые данные (хотя по факту данные будут оставаться теми же)

2021-05-20 14:56 UTC, bercly0b commented on src/pages/forum/index.tsx
> +        new TNaviItem(navLinkStart, createNaviPath(navLinkStart)),
предлагаю в навигатор просто передавать список строк, которые нужно отрендерить, а навигатор уже внутри себя будет понимать какой роут и тайтл нужно сделать под каждую строку

2021-05-20 14:57 UTC, bercly0b requested changes
пройдись пож по коментам

2021-05-21 13:20 UTC, bercly0b approved these changes

2021-05-21 13:20 UTC, merged